server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
bank.api.base-url=http://localhost:8080

resilience4j.retry.instances.bankPaymentAuthorisation.max-attempts=3
resilience4j.retry.instances.bankPaymentAuthorisation.wait-duration=500ms
resilience4j.retry.instances.bankPaymentAuthorisation.retry-exceptions=org.springframework.web.client.HttpServerErrorException,org.springframework.web.client.ResourceAccessException
resilience4j.retry.instances.bankPaymentAuthorisation.ignore-exceptions=org.springframework.web.client.HttpClientErrorException


resilience4j.circuitbreaker.instances.bankPaymentAuthorisation.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.bankPaymentAuthorisation.sliding-window-size=5
resilience4j.circuitbreaker.instances.bankPaymentAuthorisation.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.bankPaymentAuthorisation.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.bankPaymentAuthorisation.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.bankPaymentAuthorisation.record-exceptions=org.springframework.web.client.HttpServerErrorException,org.springframework.web.client.ResourceAccessException
